src/main/java/com/addcel/mx/telecomcrm/model/admin/Register.java
package com.addcel.mx.telecomcrm.model.admin;

/**
 *
 * @author Lasar-Soporte
 */
public class Register {
    
    private String tarjeta_compra;
    private String bit_fecha;
    private String bit_hora;
    private String bit_concepto;
    private int bit_codigo_error;
    private double bit_cargo;
    private double cargo_Aplicado;
    private double Comision;
    private String num_Tarjeta_Autorizacion;
    private String num_TarjetaIAVE_autorizacion;
    private String transaccion;
    private String Autorizacion;
    private String destino;

    public String getTarjeta_compra() {
        return tarjeta_compra;
    }

    public void setTarjeta_compra(String tarjeta_compra) {
        this.tarjeta_compra = tarjeta_compra;
    }

    public String getBit_fecha() {
        return bit_fecha;
    }

    public void setBit_fecha(String bit_fecha) {
        this.bit_fecha = bit_fecha;
    }

    public String getBit_hora() {
        return bit_hora;
    }

    public void setBit_hora(String bit_hora) {
        this.bit_hora = bit_hora;
    }

    public String getBit_concepto() {
        return bit_concepto;
    }

    public void setBit_concepto(String bit_concepto) {
        this.bit_concepto = bit_concepto;
    }

    public int getBit_codigo_error() {
        return bit_codigo_error;
    }

    public void setBit_codigo_error(int bit_codigo_error) {
        this.bit_codigo_error = bit_codigo_error;
    }

    public double getBit_cargo() {
        return bit_cargo;
    }

    public void setBit_cargo(double bit_cargo) {
        this.bit_cargo = bit_cargo;
    }

    public double getCargo_Aplicado() {
        return cargo_Aplicado;
    }

    public void setCargo_Aplicado(double cargo_Aplicado) {
        this.cargo_Aplicado = cargo_Aplicado;
    }

    public double getComision() {
        return Comision;
    }

    public void setComision(double Comision) {
        this.Comision = Comision;
    }

    public String getNum_Tarjeta_Autorizacion() {
        return num_Tarjeta_Autorizacion;
    }

    public void setNum_Tarjeta_Autorizacion(String num_Tarjeta_Autorizacion) {
        this.num_Tarjeta_Autorizacion = num_Tarjeta_Autorizacion;
    }

    public String getNum_TarjetaIAVE_autorizacion() {
        return num_TarjetaIAVE_autorizacion;
    }

    public void setNum_TarjetaIAVE_autorizacion(String num_TarjetaIAVE_autorizacion) {
        this.num_TarjetaIAVE_autorizacion = num_TarjetaIAVE_autorizacion;
    }

    public String getTransaccion() {
        return transaccion;
    }

    public void setTransaccion(String transaccion) {
        this.transaccion = transaccion;
    }

    public String getAutorizacion() {
        return Autorizacion;
    }

    public void setAutorizacion(String Autorizacion) {
        this.Autorizacion = Autorizacion;
    }

    public String getDestino() {
        return destino;
    }

    public void setDestino(String destino) {
        this.destino = destino;
    }
    
    
    
}

src/main/java/com/addcel/mx/telecomcrm/model/admin/UserTag.java
package com.addcel.mx.telecomcrm.model.admin;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 *
 * @author Lasar-Soporte
 */
@Entity
@Table(name = "t_usuario_tags")
public class UserTag {
    private Long id_usuario; 
    private Integer id_tiporecargatag;
    private String etiqueta; 
    private String tag; 
    private Integer dv;
    private Integer id;

    public Long getId_usuario() {
        return id_usuario;
    }

    public void setId_usuario(Long id_usuario) {
        this.id_usuario = id_usuario;
    }

    public Integer getId_tiporecargatag() {
        return id_tiporecargatag;
    }

    public void setId_tiporecargatag(Integer id_tiporecargatag) {
        this.id_tiporecargatag = id_tiporecargatag;
    }

    public String getEtiqueta() {
        return etiqueta;
    }

    public void setEtiqueta(String etiqueta) {
        this.etiqueta = etiqueta;
    }

    public String getTag() {
        return tag;
    }

    public void setTag(String tag) {
        this.tag = tag;
    }

    public Integer getDv() {
        return dv;
    }

    public void setDv(Integer dv) {
        this.dv = dv;
    }

    @Id
    @Column(name="id")
    @GeneratedValue(strategy=GenerationType.AUTO)
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }
    
    
}

src/main/java/com/addcel/mx/telecomcrm/controller/HomeController.java
package com.addcel.mx.telecomcrm.controller;

import com.addcel.mx.telecomcrm.model.UserForAuth;
import java.util.List;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.servlet.ModelAndView;

/**
 *
 * @author Lasar-Soporte
 */
@RestController
public class HomeController {

    @RequestMapping(value = "/", method = RequestMethod.GET)
    public ModelAndView homePage(HttpServletRequest request, HttpServletResponse response) {

        ModelAndView mav = new ModelAndView("login");
        Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
        
        if (!authentication.getPrincipal().equals("anonymousUser")) {
            System.out.println("User: " + SecurityContextHolder.getContext().getAuthentication().getPrincipal());

            UserForAuth user = (UserForAuth) SecurityContextHolder.getContext().getAuthentication().getPrincipal();

            System.out.println("Auth " + user.getAuthorities().toString());

            List<GrantedAuthority> roles = user.getAuthorities();            
            for (GrantedAuthority authority : roles) {
                if ("ROLE_ADMIN".equals(authority.getAuthority())) {
                    mav = new ModelAndView("admin/index");
                } else if ("ROLE_PROVEEDOR".equals(authority.getAuthority())) {
                    mav = new ModelAndView("provider/index");
                }
            }
        }

        return mav;
    }

    @RequestMapping(value = "/proveedor", method = RequestMethod.GET)
    public ModelAndView homeProviderView(HttpServletRequest request, HttpServletResponse response) throws Exception {

        ModelAndView mav = new ModelAndView("provider/index");
        return mav;
    }

    @RequestMapping(value = "/admin", method = RequestMethod.GET)
    public ModelAndView homeAdminView(HttpServletRequest request, HttpServletResponse response) throws Exception {

        ModelAndView mav = new ModelAndView("admin/index");
        return mav;
    }
}

src/main/java/com/addcel/mx/telecomcrm/controller/admin/ClientController.java
package com.addcel.mx.telecomcrm.controller.admin;

import com.addcel.mx.telecomcrm.model.admin.Client;
import com.addcel.mx.telecomcrm.model.admin.ClientCard;
import com.addcel.mx.telecomcrm.model.admin.ClientSearch;
import com.addcel.mx.telecomcrm.model.admin.ClientStatus;
import com.addcel.mx.telecomcrm.model.admin.LockedCard;
import com.addcel.mx.telecomcrm.service.ClientCardService;
import com.addcel.mx.telecomcrm.service.ClientCardServiceImpl;
import com.addcel.mx.telecomcrm.service.ClientService;
import com.addcel.mx.telecomcrm.service.LockService;
import com.addcel.mx.telecomcrm.utils.Crypto;
import java.sql.Timestamp;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.servlet.ModelAndView;

/**
 *
 * @author wsolano
 */

@RestController
@RequestMapping(value="/admin/cliente")
public class ClientController {
    
    @Autowired
    private ClientService clientService;
    
    @Autowired
    private ClientCardServiceImpl clientCardService;
    
    @Autowired
    private LockService lockService;
    
    @RequestMapping(value="/", method=RequestMethod.GET)
    public ModelAndView homeAdminViewTemplate(HttpServletRequest request, HttpServletResponse response) throws Exception {                                 
        ModelAndView mav = new ModelAndView("admin/client");                         
        return mav;
    }
    
    @RequestMapping(value="/detail", method=RequestMethod.GET)
    public ModelAndView detailClientViewTemplate(HttpServletRequest request, HttpServletResponse response) throws Exception {                                 
        ModelAndView mav = new ModelAndView("admin/templates/clientTemplate");                         
        return mav;
    }
    
    @RequestMapping(value = "/list", method = RequestMethod.GET)
    public ResponseEntity<List<Client>> listAllClients() throws Exception {                                
                
        List<Client> clients = new ArrayList<>();                                             
        
        clients = clientService.listClients();                   
        if(clients.isEmpty()){
            return new ResponseEntity<>(HttpStatus.NO_CONTENT);//You many decide to return HttpStatus.NOT_FOUND
        }
        
        return new ResponseEntity<>(clients, HttpStatus.OK);
    }
    
    @RequestMapping(value = "/list", method = RequestMethod.POST)
    public ResponseEntity<List<Client>> getClientsByPage(@RequestBody int [] data) throws Exception {                                
                
        List<Client> clients = new ArrayList<>();                                             
        
        //System.out.println("page " + data[0]);
        //System.out.println("max " + data[1]);
        
        clients = clientService.getPageClients(data[0], data[1]);                   
        if(clients.isEmpty()){
            return new ResponseEntity<>(HttpStatus.NO_CONTENT);//You many decide to return HttpStatus.NOT_FOUND
        }
        
        return new ResponseEntity<>(clients, HttpStatus.OK);
    }
    
    @RequestMapping(value = "/clientbyimei", method = RequestMethod.POST)
    public ResponseEntity<Client> getClientsByImei(@RequestBody String imei) throws Exception {                                
                
                                           
        Client client = clientService.getClientByImei(imei);                   
        if(client == null){
            return new ResponseEntity<>(HttpStatus.NO_CONTENT);//You many decide to return HttpStatus.NOT_FOUND
        }
                
        client.setUsr_tdc_numero(Crypto.escondeDigitos(client.getUsr_tdc_numero()));
                
        return new ResponseEntity<>(client, HttpStatus.OK);
    }

    @RequestMapping(value = "/clientbycard", method = RequestMethod.POST)
    public ResponseEntity<Client> getClientsByCard(@RequestBody String tarjeta) throws Exception {                                
        
        String encryptedCardNumber = tarjeta;
        if (Crypto.isNumeric(tarjeta)){            
            encryptedCardNumber = Crypto.aesEncrypt(tarjeta);                        
        }
        
        Client client = clientService.getClientByCard(encryptedCardNumber);        
        if(client == null){
            ClientCard clientCard = clientCardService.getClientCardByNumberCard(encryptedCardNumber);
            if (clientCard != null){
                client = clientService.getClientById(clientCard.getIdusuario());
            }else{
                return new ResponseEntity<>(HttpStatus.NO_CONTENT);//You many decide to return HttpStatus.NOT_FOUND
            }
        }
        
        if (!Crypto.isNumeric(client.getUsr_tdc_numero())){
            client.setUsr_tdc_numero(tarjeta);
        }
        
        return new ResponseEntity<>(client, HttpStatus.OK);
    }
    
    @RequestMapping(value = "/clientbyid", method = RequestMethod.POST)
    public ResponseEntity<Client> getClientsById(@RequestBody Long id) throws Exception {                                                
        
        Client client = clientService.getClientById(id);        
        if(client == null){
            return new ResponseEntity<>(HttpStatus.NO_CONTENT);//You many decide to return HttpStatus.NOT_FOUND
        }
        
        if (!Crypto.isNumeric(client.getUsr_tdc_numero())){
            client.setUsr_tdc_numero(Crypto.escondeDigitos(client.getUsr_tdc_numero()));
        }
        
        return new ResponseEntity<>(client, HttpStatus.OK);
    }
    
    @RequestMapping(value = "/total", method = RequestMethod.POST)
    public ResponseEntity<?> getNumberOfClients() throws Exception {                                                                                                            
        
        Long totalClients = clientService.getNumberRows();
        return new ResponseEntity<>(totalClients, HttpStatus.OK);
    }
    
    @RequestMapping(value = "/edit", method = RequestMethod.POST)
    public ResponseEntity<Client> editClient(@RequestBody Client client) throws Exception {                                
        /*
        System.out.println("Registro " + client.getUsr_fecha_registro());
        System.out.println("Nacimiento " + client.getUsr_fecha_nac());
        
        System.out.println("numero de tarjeta " + client.getUsr_tdc_numero());
        System.out.println("numero de tarjeta numerico " + Crypto.isNumeric(client.getUsr_tdc_numero()));
        */
        if (Crypto.isNumeric(client.getUsr_tdc_numero())){
            String encryptedCardNumber = Crypto.aesEncrypt(client.getUsr_tdc_numero());
            client.setUsr_tdc_numero(encryptedCardNumber);
        }else{
            Client clientAux = clientService.getClientById(client.getId_usuario());
            client.setUsr_tdc_numero(clientAux.getUsr_tdc_numero());
        }               
        
        if (Crypto.isNumeric(client.getUsr_pwd())){            
            client.setUsr_pwd(Crypto.aesEncrypt(client.getUsr_pwd()));
        }
        
        clientService.updateClient(client);                               
        
        Client clientToResponse = clientService.getClientById(client.getId_usuario());        
        String cardNumber = Crypto.escondeDigitos(clientToResponse.getUsr_tdc_numero());                                    
        clientToResponse.setUsr_tdc_numero(cardNumber);
        
        return new ResponseEntity<>(clientToResponse, HttpStatus.OK);
    }
    
    @RequestMapping(value = "/add", method = RequestMethod.POST)
    public ResponseEntity<Client> addClient(@RequestBody Client client) throws Exception {                                
        
        if (Crypto.isNumeric(client.getUsr_tdc_numero())){            
            client.setUsr_tdc_numero(Crypto.aesEncrypt(client.getUsr_tdc_numero()));
        }
        
        if (Crypto.isNumeric(client.getUsr_pwd())){            
            client.setUsr_pwd(Crypto.aesEncrypt(client.getUsr_pwd()));
        }                        
        
        Timestamp timestamp = new Timestamp(System.currentTimeMillis());
        System.out.println("Fecha de registro " + timestamp);                
        client.setUsr_fecha_registro(timestamp);
        
        clientService.addClient(client);                               
                
        return new ResponseEntity<>(client, HttpStatus.OK);
    }
    
    @RequestMapping(value = "/searchClients", method = RequestMethod.POST)
    public ResponseEntity<List<Client>> searchClients(@RequestBody ClientSearch clientSearch) throws Exception {                                
                
        List<Client> clients = new ArrayList<>();                                                             
        
        clients = clientService.searchClients(clientSearch); 
        //System.out.println("CLients size " + clients.size());
        if(clients.isEmpty()){
            return new ResponseEntity<>(HttpStatus.NO_CONTENT);//You many decide to return HttpStatus.NOT_FOUND
        }
        
        for (Client client : clients){            
            //System.out.println("Tarjeta " + client.getUsr_tdc_numero() + 
              //      " desencriptada " + Crypto.getCardNumber(client.getUsr_tdc_numero()));

src/main/webapp/WEB-INF/views/admin/home.jsp
<%--
    Document   : home
    Created on : 19/03/2017, 09:29:53 PM
    Author     : Lasar-Soporte
--%>

<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<header id="mainHeader" class="w3-center w3-text-white">
    <h4 class="w3-padding-8" >Módulo Administrador</h4>                
</header>
<div class="w3-center">
    <h5 class="w3-text-grey">
        Bienvenido al portal administrativo de Telecom, en el menu desplegable
        ubicado en el panel a tu izquierda se encuentran las opciones disponibles.
    </h5>
</div>

src/main/webapp/WEB-INF/views/admin/provider.jsp
<%-- 
    Document   : provider
    Created on : 26/03/2017, 11:40:04 AM
    Author     : Lasar-Soporte
--%>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<div ng-controller="ProviderController as ctrl">
    <header id="mainHeader" class="w3-center w3-text-white">                
        <h4 class="w3-padding-8" >Módulo Administrador - Proveedores</h4>                
    </header>
    <div class="w3-center" ng-show="ctrl.wait">
        <i class="fa fa-spinner w3-xxxlarge w3-spin" aria-hidden="true"></i>
    </div>
    <div class="w3-margin" ng-hide="ctrl.wait">                        
        <table id="providersTable" datatable="ng" 
               dt-options="ctrl.dtProviderOptions" dt-column-defs="ctrl.dtProviderColumnDefs" 
               dt-instance="ctrl.dtProviderInstance"
               class="table-responsive table-bordered w3-tiny">
            <thead>
                <tr class="table-header w3-padding-0">            
                    <th class="w3-text-white w3-padding-2 w3-center">ID</th>
                    <th class="w3-text-white w3-padding-2 w3-center">Nombre Comercio</th>
                    <th class="w3-text-white w3-padding-2 w3-center">Comisión</th>                                       
                    <th class="w3-text-white w3-padding-2 w3-center">
                        <a href="" class="w3-hover-opacity w3-padding-2 w3-center w3-text-white"
                           uib-tooltip="Agregar Proveedor" data-toggle="modal" data-target="#providerModal"
                           ng-click="ctrl.initProviderModalData('', 'create')">
                            <i class="material-icons" >                            
                                add
                            </i>                            
                        </a>
                    </th>                
                </tr>
            </thead>
            <tbody>
                <tr ng-repeat="provider in ctrl.providers track by provider.id_proveedor" 
                    class="w3-hover-orange w3-padding-0 w3-center">            
                    <td class="w3-padding-2 w3-center">{{ provider.id_proveedor }}</td>
                    <td class="w3-padding-2 w3-center">{{ provider.prv_nombre_comercio }}</td>
                    <td class="w3-padding-2 w3-center">{{ provider.comision }}</td>                                      
                    <td class="w3-padding-2 w3-center">
                        <a href="" class="w3-hover-opacity w3-padding-2 w3-tiny" 
                           uib-tooltip="Detalles" data-toggle="modal" data-target="#providerModal"
                           ng-click="ctrl.initProviderModalData(provider, 'detail')">
                            <i class="material-icons w3-text-blue">                            
                                search
                            </i>                            
                        </a>
                        <a href="" class="w3-hover-opacity w3-padding-2 w3-tiny" 
                           uib-tooltip="Editar" data-toggle="modal" data-target="#providerModal"
                           ng-click="ctrl.initProviderModalData(provider, 'edit')">
                            <i class="material-icons w3-text-green">                            
                                mode_edit
                            </i>                            
                        </a>                                               
                    </td>         
                </tr>
            </tbody>
        </table>
    </div>
    <div id="providerModal" class="modal fade" role="dialog">
        <div ng-include="'/TelecomCRM/admin/provider/detail'"></div>
    </div>
</div>

src/main/webapp/WEB-INF/views/admin/reverseTransaction.jsp
<%-- 
    Document   : reverseTransaction
    Created on : 24-mar-2017, 11:03:17
    Author     : wsolano
--%>

<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<div ng-controller="ReverseTransactionController as ctrl">
    <header id="mainHeader" class="w3-center w3-text-white">                
        <h4 class="w3-padding-8" >Módulo Administrador - Reversos</h4>                
    </header>
    <div class="w3-center" ng-show="ctrl.wait">
        <i class="fa fa-spinner w3-xxxlarge w3-spin" aria-hidden="true"></i>
    </div>
    <div class="w3-margin w3-small" ng-if="ctrl.search && !ctrl.wait">        
        <form class="form-group col-lg-12 col-md-12 col-sm-12 test">
            <div>                               
                <!-- busqueda por nombre completo-->
                <div class="w3-margin ">
                    <div class="form-group">
                        <label class="w3-label">Busqueda por nombre y/o apellido</label>                                               
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-sm-12">
                                <label class="">Nombre:</label>
                                <input class="form-control" type="text" name="usr_nombre" id="usr_nombre" value=""
                                        placeholder="Nombre" ng-model="ctrl.reverseTransactionSearch.usr_nombre" />                                
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-12">
                                <label class="">Apellido:</label>                                
                                <input class="form-control" type="text" name="usr_apellido" id="usr_apellido" value=""
                                        placeholder="Apellido" ng-model="ctrl.reverseTransactionSearch.usr_apellido" />
                            </div>                                                 
                        </div>
                    </div>
                </div>                
                <!-- busqueda por rango de fecha-->
                <div class="w3-margin ">
                    <div class="form-group">
                        <label class="w3-label">Búsqueda por fecha:</label>                                                
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-sm-12">
                                <label class="">Desde:</label>
                                <p class="input-group">                                    
                                    <input type="text" class="form-control" uib-datepicker-popup
                                           ng-model="ctrl.reverseTransactionSearch.fechaHora_inicial" 
                                           is-open="ctrl.initialDate.opened"  
                                           ng-required="false" close-text="Cerrar" />
                                    <span class="input-group-btn">
                                        <button type="button" class="btn btn-default" 
                                                ng-click="ctrl.openInitialDate()">
                                            <i class="glyphicon glyphicon-calendar"></i>
                                        </button>
                                    </span>                                     
                                </p>
                            </div>

                            <div class="col-lg-6 col-md-6 col-sm-12">
                                <label class="">Hasta:</label>
                                <p class="input-group">                                    
                                    <input type="text" class="form-control" uib-datepicker-popup 
                                           ng-model="ctrl.reverseTransactionSearch.fechaHora_final" 
                                           is-open="ctrl.finalDate.opened"
                                           ng-required="false" close-text="Cerrar" />
                                    <span class="input-group-btn">
                                        <button type="button" class="btn btn-default" 
                                                ng-click="ctrl.openFinalDate()">
                                            <i class="glyphicon glyphicon-calendar"></i>
                                        </button>
                                    </span>
                                </p>
                            </div>
                        </div>                        
                    </div>
                </div>                
                <div class="w3-margin ">
                    <div class="form-group">
                        <button type="button" class="btn btn-raised btn-secondary" value="Buscar" 
                                ng-click="ctrl.searchReverseTransactionByParameters()"
                        ng-disabled="ctrl.validateReverseTransactionSearch()">Buscar</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <div class="w3-margin" ng-if="ctrl.finishedSearch && !ctrl.wait">                        
        <table id="reverseTransactionsTable" datatable="ng" 
               dt-options="ctrl.dtOptions" dt-column-defs="ctrl.dtColumnDefs" dt-instance="ctrl.dtInstance"
               class="table-responsive table-bordered w3-tiny">
            <thead>
                <tr class="table-header w3-padding-0">            
                    <th class="w3-text-white w3-padding-2 w3-center">ID</th>
                    <th class="w3-text-white w3-padding-2 w3-center">Usuario</th>
                    <th class="w3-text-white w3-padding-2 w3-center">Secuencia</th>
                    <th class="w3-text-white w3-padding-2 w3-center">Fecha</th>
                    <th class="w3-text-white w3-padding-2 w3-center">Autorización</th>
                    <th class="w3-text-white w3-padding-2 w3-center">Clave operación</th>
                    <th class="w3-text-white w3-padding-2 w3-center">Clave venta</th>                    
                    <th class="w3-text-white w3-padding-2 w3-center">                        
                    </th>                
                </tr>
            </thead>
            <tbody>
                <tr ng-repeat="reverseTransaction in ctrl.reverseTransactions track by reverseTransaction.id_bitacora" 
                    class="w3-hover-orange w3-padding-0 w3-center">            
                    <td class="w3-padding-2 w3-center">{{ reverseTransaction.id_bitacora }}</td>
                    <td class="w3-padding-2 w3-center">{{ reverseTransaction.id_usuario }}</td>
                    <td class="w3-padding-2 w3-center">{{ reverseTransaction.secuencia }}</td>
                    <td class="w3-padding-2 w3-center">{{ reverseTransaction.fechahora }}</td>
                    <td class="w3-padding-2 w3-center">{{ reverseTransaction.autorizacion }}</td>
                    <td class="w3-padding-2 w3-center">{{ reverseTransaction.claveoperacion }}</td>
                    <td class="w3-padding-2 w3-center">{{ reverseTransaction.claveventa }}</td>                    
                    <td class="w3-padding-2 w3-center">
                        <a href="" class="w3-hover-opacity w3-padding-2 w3-tiny" 
                           uib-tooltip="Detalles" data-toggle="modal" data-target="#reverseTransactionModal"
                           ng-click="ctrl.initReverseTransactionModalData(reverseTransaction)">
                            <i class="material-icons w3-text-blue">                            
                                search
                            </i>                            
                        </a>                                               
                    </td>         
                </tr>
            </tbody>
        </table>
    </div>
    <div id="reverseTransactionModal" class="modal fade" role="dialog">
        <div ng-include="'/TelecomCRM/admin/reverso/detail'"></div>
    </div>
</div>